### ISSUE TITLE
League Training for SlimeVolleyball Env

### ISSUE THREAD

**Issue by PaParaZz1** [opendilab/DI-engine#90]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc]()
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

## Overview
Add league training pipeline in slime_volleyball environment, and make better performance than self-play results (#23)
Related Discussion: #61 

## TODO

- [ ] league pipeline
- [ ] mutate from pre-trained model (vs bot)
- [ ] policy behavior analysis

**Comment by PaParaZz1** [comment]
we will restart this demo in February 28th, and we expect to finish it in a week.

**Comment by zxzzz0** [comment]
@PaParaZz1 Could we have some updates on this? It's been more than 8 weeks.

**Comment by zxzzz0** [comment]
> we will restart this demo in February 28th, and we expect to finish it in a week.

@PaParaZz1 it's been 6 months, do we complete the tasks below?

- [ ] league pipeline
- [ ] mutate from pre-trained model (vs bot)
- [ ] policy behavior analysis
